<?php
/**
 * Amazon Marketplace Pro
 *
 * NOTICE OF LICENCE
 *
 * This software is commercial and licensed, not sold. The licence is
 * bundled with this package in the file LICENSE.txt. Redistribution,
 * resale and publication of the source are prohibited.
 *
 *  @author    IntelliPresta
 *  @copyright 2026 IntelliPresta
 *  @license   Proprietary. See LICENSE.txt - redistribution prohibited.
 */

/**
 * Build translations/<iso>.php from the translation data in data/.
 *
 *     php tools/i18n/build.php
 *
 * The key and the escaping below are read from PrestaShop's own source, which
 * is open source (AFL/OSL). In Translate::getModuleTranslation()
 * (classes/Translate.php, PrestaShop 1.6.1.24 lines 158-172 and PrestaShop
 * 9.1.5 lines 114-122, identical logic) each lookup is
 *
 *     $string = preg_replace("/\\*'/", "\'", $string);
 *     $key = md5($string);
 *     $defaultKey = strtolower('<{' . $name . '}prestashop>' . $source) . '_' . $key;
 *
 * and the stored value is returned through stripslashes(). So the md5 covers
 * the English text with its apostrophes backslash-escaped.
 *
 * `source` is where the string sits, and the callers decide it:
 * - a template passes basename($filename, '.tpl') - smartyTranslate() in
 *   config/smartyadmin.config.inc.php - so configure.tpl gives "configure";
 * - Module::l() (classes/module/Module.php) passes the module name, or the
 *   $specific argument when one is given, which is what AmazonI18n uses for
 *   the plain classes.
 *
 * Both versions read translations/<iso>.php, which is why one legacy file per
 * language serves every PrestaShop the module supports.
 *
 * Because the key is an md5 of the English source, editing an English string
 * in a template silently orphans its line here. Re-run this script after any
 * such edit; it refuses to write while any string is untranslated, so the
 * orphan cannot pass unnoticed.
 */
define('AMZPRO_I18N_MODULE', 'amazonmarketplacepro');

$root = dirname(dirname(__DIR__)) . '/';
$dest = $root . 'translations/';
$langs = array('fr', 'es', 'de', 'it', 'pl');

/**
 * The escaping PrestaShop applies before hashing, copied in behaviour from
 * Translate::getModuleTranslation(): preg_replace("/\\*'/", "\'", $string).
 *
 * @param string $s the English string as written in the template or class
 *
 * @return string
 */
function amzproI18nNormalise($s)
{
    return preg_replace("/\\\\*'/", "\\'", $s);
}

/**
 * @param string $source template basename, or the source the caller passes to l()
 * @param string $string the English string
 *
 * @return string the array key PrestaShop looks up in translations/<iso>.php
 */
function amzproI18nKey($source, $string)
{
    return strtolower('<{' . AMZPRO_I18N_MODULE . '}prestashop>' . $source)
        . '_' . md5(amzproI18nNormalise($string));
}

// The `source` of each file comes from amzproI18nSource() in extract.php.
$strings = require __DIR__ . '/extract.php';

// Key the data by the normalised English so a lookup cannot miss over an
// apostrophe. data/all.php lists the chunks literally and rejects duplicates.
$data = array();
foreach (require __DIR__ . '/data/all.php' as $en => $row) {
    $data[amzproI18nNormalise($en)] = $row;
}
echo count($data) . " translated strings\n";

// Every string the templates actually use must be covered.
$missing = array();
$needed = array();
foreach ($strings as $file => $list) {
    foreach ($list as $s) {
        $n = amzproI18nNormalise($s);
        $needed[$n] = true;
        if (!isset($data[$n])) {
            $missing[$n] = $file;
        }
    }
}
$extra = array_diff_key($data, $needed);
if ($extra) {
    echo "\n" . count($extra) . " translated string(s) no longer used by the templates:\n";
    foreach (array_slice(array_keys($extra), 0, 10) as $s) {
        echo '  - ' . str_replace("\n", '\n', $s) . "\n";
    }
    echo "  (harmless, but they can be deleted from data/)\n";
}
if ($missing) {
    echo "\nMISSING " . count($missing) . " translation(s) - nothing written:\n";
    foreach (array_slice($missing, 0, 40, true) as $s => $file) {
        echo '  - ' . str_replace("\n", '\n', $s) . "\n";
    }
    exit(1);
}

// Laid out the way tools/php-cs-fixer.php leaves the module's files.
$header = "<?php\n"
    . "/**\n"
    . " * Amazon Marketplace Pro\n"
    . " *\n"
    . " * NOTICE OF LICENCE\n"
    . " *\n"
    . " * This software is commercial and licensed, not sold. The licence is\n"
    . " * bundled with this package in the file LICENSE.txt. Redistribution,\n"
    . " * resale and publication of the source are prohibited.\n"
    . " *\n"
    . " *  @author    IntelliPresta\n"
    . " *  @copyright 2026 IntelliPresta\n"
    . " *  @license   Proprietary. See LICENSE.txt - redistribution prohibited.\n"
    . " */\n\n"
    . "/*\n"
    . " * %s translation, read by PrestaShop 1.6 through 9.\n"
    . " *\n"
    . " * Generated by tools/i18n/build.php - do not edit by hand: the keys are\n"
    . " * md5 hashes of the English source, so a hand-written line that does not\n"
    . " * match is simply ignored. Edit tools/i18n/data/ and rebuild.\n"
    . " */\n\n"
    // PrestaShop always includes this from a bootstrapped context, so the
    // guard costs nothing and keeps the file from answering over HTTP.
    . "if (!defined('_PS_VERSION_')) {\n    exit;\n}\n\n";

$names = array('fr' => 'French', 'es' => 'Spanish', 'de' => 'German', 'it' => 'Italian', 'pl' => 'Polish');

foreach ($langs as $lang) {
    $lines = array();
    $seen = array();
    foreach ($strings as $file => $list) {
        $source = amzproI18nSource($file);
        foreach ($list as $s) {
            $row = $data[amzproI18nNormalise($s)];
            if (!isset($row[$lang]) || trim($row[$lang]) === '') {
                fwrite(STDERR, "no $lang translation for: $s\n");
                exit(1);
            }
            $key = amzproI18nKey($source, $s);
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;
            // PrestaShop stripslashes() the value on read, so store it slashed.
            $lines[] = "\$_MODULE['" . $key . "'] = '" . addslashes($row[$lang]) . "';";
        }
    }

    $out = sprintf($header, $names[$lang])
        . "global \$_MODULE;\n"
        . "\$_MODULE = [];\n\n"
        . implode("\n", $lines) . "\n";

    file_put_contents($dest . $lang . '.php', $out);
    echo str_pad($lang, 4) . str_pad(count($lines) . ' keys', 12) . strlen($out) . " bytes\n";
}
echo "done - now run tools/i18n/verify.php for each language\n";
